services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    profiles:
      - database
  
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=teste
      - MYSQL_ROOT_PASSWORD=1003
      - MYSQL_PASSWORD=1003
      - MYSQL_DATABASE=teste_db      
    ports:
      - "3309:3306"
    volumes:
      - ./database/data/mysql:/var/lib/mysql
    profiles:
      - database